name: Semgrep Java Code Scan

on:
  push:
    branches: [master-cloud]
  pull_request:
    branches: [master-cloud]

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v4

      # 使用指定规则集
      - run: semgrep ci --config "p/java" --config "p/security-audit" --config "p/trailofbits"
        continue-on-error: true
